### ISSUE TITLE
fix: Blender 4.2.0 compatibility

### ISSUE THREAD

**Issue by SAEEDAMANIFX** [GixoXYZ/BlenderGBHTool#45]
Hello Gixo team,

I recently purchased the GBH Tool for Blender, but it doesn’t work with Blender 4.2. Please let me know when the tool will be updated to support this version.

Thank you for being so understanding, and I look forward to your response.

<img width="598" alt="Screenshot 2024-09-24 at 8 09 41 PM" src="https://github.com/user-attachments/assets/a7cc2e3c-cad3-4324-a6c4-a2fe7749bc19">

**Comment by GixoXYZ** [comment]
Hello, and thank you for your purchase! I apologize for the delayed response.

To ensure everything functions smoothly, I recommend to update to Blender v4.2.1 ro later, as future developments of the GBH Tool will be based on this version.

However, if you need to continue using Blender v4.2.0 for your workflow, you should be able to install the tool using this file:
[BlenderGBHTool_v2.2.0_Blender_4.2.0.zip](https://mega.nz/file/NYNDVKCL#PyZzavNWCECgUyjYabE4iLnJ8a9V3iZIKQc5t5HWBTg)

Feel free to reach out if you encounter any further issues. I'm happy to help!
